version: '3.8'

services:
  login-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=clave_secreta
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
